// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package top.zopx.goku.example.socket.proto.auth;

public final class Auth {
  private Auth() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code auth.AuthDef}
   */
  public enum AuthDef
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>_Dummy = 0;</code>
     */
    _Dummy(0),
    /**
     * <code>_LoginRequest = 100;</code>
     */
    _LoginRequest(100),
    /**
     * <code>_LoginResponse = 101;</code>
     */
    _LoginResponse(101),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>_Dummy = 0;</code>
     */
    public static final int _Dummy_VALUE = 0;
    /**
     * <code>_LoginRequest = 100;</code>
     */
    public static final int _LoginRequest_VALUE = 100;
    /**
     * <code>_LoginResponse = 101;</code>
     */
    public static final int _LoginResponse_VALUE = 101;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AuthDef valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static AuthDef forNumber(int value) {
      switch (value) {
        case 0: return _Dummy;
        case 100: return _LoginRequest;
        case 101: return _LoginResponse;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AuthDef>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AuthDef> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AuthDef>() {
            public AuthDef findValueByNumber(int number) {
              return AuthDef.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return top.zopx.goku.example.socket.proto.auth.Auth.getDescriptor().getEnumTypes().get(0);
    }

    private static final AuthDef[] VALUES = values();

    public static AuthDef valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AuthDef(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:auth.AuthDef)
  }

  public interface LoginRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:auth.LoginRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 登录方式,
     * 0 = 测试登录, 1 = 账密登录, 2 = Ukey 登录, 3 = 手机号+验证码登录, 4 = 微信登录, 5 = 微信公众号登录, 6 = auth中台登录
     * </pre>
     *
     * <code>sint32 loginType = 1;</code>
     * @return The loginType.
     */
    int getLoginType();

    /**
     * <pre>
     * JSON 字符串, 可能会包含用户名称和密码
     * </pre>
     *
     * <code>string login = 2;</code>
     * @return The login.
     */
    java.lang.String getLogin();
    /**
     * <pre>
     * JSON 字符串, 可能会包含用户名称和密码
     * </pre>
     *
     * <code>string login = 2;</code>
     * @return The bytes for login.
     */
    com.google.protobuf.ByteString
        getLoginBytes();
  }
  /**
   * <pre>
   * Ping 
   * =========================== //
   * 指令
   * </pre>
   *
   * Protobuf type {@code auth.LoginRequest}
   */
  public static final class LoginRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:auth.LoginRequest)
      LoginRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LoginRequest.newBuilder() to construct.
    private LoginRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginRequest() {
      login_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LoginRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LoginRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              loginType_ = input.readSInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              login_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return top.zopx.goku.example.socket.proto.auth.Auth.internal_static_auth_LoginRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return top.zopx.goku.example.socket.proto.auth.Auth.internal_static_auth_LoginRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest.class, top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest.Builder.class);
    }

    public static final int LOGINTYPE_FIELD_NUMBER = 1;
    private int loginType_;
    /**
     * <pre>
     * 登录方式,
     * 0 = 测试登录, 1 = 账密登录, 2 = Ukey 登录, 3 = 手机号+验证码登录, 4 = 微信登录, 5 = 微信公众号登录, 6 = auth中台登录
     * </pre>
     *
     * <code>sint32 loginType = 1;</code>
     * @return The loginType.
     */
    @java.lang.Override
    public int getLoginType() {
      return loginType_;
    }

    public static final int LOGIN_FIELD_NUMBER = 2;
    private volatile java.lang.Object login_;
    /**
     * <pre>
     * JSON 字符串, 可能会包含用户名称和密码
     * </pre>
     *
     * <code>string login = 2;</code>
     * @return The login.
     */
    @java.lang.Override
    public java.lang.String getLogin() {
      java.lang.Object ref = login_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        login_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * JSON 字符串, 可能会包含用户名称和密码
     * </pre>
     *
     * <code>string login = 2;</code>
     * @return The bytes for login.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLoginBytes() {
      java.lang.Object ref = login_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        login_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (loginType_ != 0) {
        output.writeSInt32(1, loginType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(login_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, login_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (loginType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, loginType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(login_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, login_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest)) {
        return super.equals(obj);
      }
      top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest other = (top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest) obj;

      if (getLoginType()
          != other.getLoginType()) return false;
      if (!getLogin()
          .equals(other.getLogin())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LOGINTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getLoginType();
      hash = (37 * hash) + LOGIN_FIELD_NUMBER;
      hash = (53 * hash) + getLogin().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Ping 
     * =========================== //
     * 指令
     * </pre>
     *
     * Protobuf type {@code auth.LoginRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:auth.LoginRequest)
        top.zopx.goku.example.socket.proto.auth.Auth.LoginRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return top.zopx.goku.example.socket.proto.auth.Auth.internal_static_auth_LoginRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return top.zopx.goku.example.socket.proto.auth.Auth.internal_static_auth_LoginRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest.class, top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest.Builder.class);
      }

      // Construct using top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        loginType_ = 0;

        login_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return top.zopx.goku.example.socket.proto.auth.Auth.internal_static_auth_LoginRequest_descriptor;
      }

      @java.lang.Override
      public top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest getDefaultInstanceForType() {
        return top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest.getDefaultInstance();
      }

      @java.lang.Override
      public top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest build() {
        top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest buildPartial() {
        top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest result = new top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest(this);
        result.loginType_ = loginType_;
        result.login_ = login_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest) {
          return mergeFrom((top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest other) {
        if (other == top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest.getDefaultInstance()) return this;
        if (other.getLoginType() != 0) {
          setLoginType(other.getLoginType());
        }
        if (!other.getLogin().isEmpty()) {
          login_ = other.login_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int loginType_ ;
      /**
       * <pre>
       * 登录方式,
       * 0 = 测试登录, 1 = 账密登录, 2 = Ukey 登录, 3 = 手机号+验证码登录, 4 = 微信登录, 5 = 微信公众号登录, 6 = auth中台登录
       * </pre>
       *
       * <code>sint32 loginType = 1;</code>
       * @return The loginType.
       */
      @java.lang.Override
      public int getLoginType() {
        return loginType_;
      }
      /**
       * <pre>
       * 登录方式,
       * 0 = 测试登录, 1 = 账密登录, 2 = Ukey 登录, 3 = 手机号+验证码登录, 4 = 微信登录, 5 = 微信公众号登录, 6 = auth中台登录
       * </pre>
       *
       * <code>sint32 loginType = 1;</code>
       * @param value The loginType to set.
       * @return This builder for chaining.
       */
      public Builder setLoginType(int value) {
        
        loginType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 登录方式,
       * 0 = 测试登录, 1 = 账密登录, 2 = Ukey 登录, 3 = 手机号+验证码登录, 4 = 微信登录, 5 = 微信公众号登录, 6 = auth中台登录
       * </pre>
       *
       * <code>sint32 loginType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLoginType() {
        
        loginType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object login_ = "";
      /**
       * <pre>
       * JSON 字符串, 可能会包含用户名称和密码
       * </pre>
       *
       * <code>string login = 2;</code>
       * @return The login.
       */
      public java.lang.String getLogin() {
        java.lang.Object ref = login_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          login_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * JSON 字符串, 可能会包含用户名称和密码
       * </pre>
       *
       * <code>string login = 2;</code>
       * @return The bytes for login.
       */
      public com.google.protobuf.ByteString
          getLoginBytes() {
        java.lang.Object ref = login_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          login_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * JSON 字符串, 可能会包含用户名称和密码
       * </pre>
       *
       * <code>string login = 2;</code>
       * @param value The login to set.
       * @return This builder for chaining.
       */
      public Builder setLogin(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        login_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * JSON 字符串, 可能会包含用户名称和密码
       * </pre>
       *
       * <code>string login = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLogin() {
        
        login_ = getDefaultInstance().getLogin();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * JSON 字符串, 可能会包含用户名称和密码
       * </pre>
       *
       * <code>string login = 2;</code>
       * @param value The bytes for login to set.
       * @return This builder for chaining.
       */
      public Builder setLoginBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        login_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:auth.LoginRequest)
    }

    // @@protoc_insertion_point(class_scope:auth.LoginRequest)
    private static final top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest();
    }

    public static top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginRequest>
        PARSER = new com.google.protobuf.AbstractParser<LoginRequest>() {
      @java.lang.Override
      public LoginRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public top.zopx.goku.example.socket.proto.auth.Auth.LoginRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:auth.LoginResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 用户 Id,
     * 如果是 -1 则说明登录失败
     * </pre>
     *
     * <code>int64 userId = 1;</code>
     * @return The userId.
     */
    long getUserId();

    /**
     * <pre>
     * 用户名称
     * </pre>
     *
     * <code>string userName = 2;</code>
     * @return The userName.
     */
    java.lang.String getUserName();
    /**
     * <pre>
     * 用户名称
     * </pre>
     *
     * <code>string userName = 2;</code>
     * @return The bytes for userName.
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <pre>
     * 入场票据
     * </pre>
     *
     * <code>string ticket = 3;</code>
     * @return The ticket.
     */
    java.lang.String getTicket();
    /**
     * <pre>
     * 入场票据
     * </pre>
     *
     * <code>string ticket = 3;</code>
     * @return The bytes for ticket.
     */
    com.google.protobuf.ByteString
        getTicketBytes();

    /**
     * <pre>
     * 数字证书字符串
     * </pre>
     *
     * <code>string ukey = 4;</code>
     * @return The ukey.
     */
    java.lang.String getUkey();
    /**
     * <pre>
     * 数字证书字符串
     * </pre>
     *
     * <code>string ukey = 4;</code>
     * @return The bytes for ukey.
     */
    com.google.protobuf.ByteString
        getUkeyBytes();

    /**
     * <pre>
     * 数字正说过期时间
     * </pre>
     *
     * <code>sint64 ukeyExpireAt = 5;</code>
     * @return The ukeyExpireAt.
     */
    long getUkeyExpireAt();
  }
  /**
   * <pre>
   * 响应结果
   * </pre>
   *
   * Protobuf type {@code auth.LoginResponse}
   */
  public static final class LoginResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:auth.LoginResponse)
      LoginResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LoginResponse.newBuilder() to construct.
    private LoginResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LoginResponse() {
      userName_ = "";
      ticket_ = "";
      ukey_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new LoginResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LoginResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              userId_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              ticket_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              ukey_ = s;
              break;
            }
            case 40: {

              ukeyExpireAt_ = input.readSInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return top.zopx.goku.example.socket.proto.auth.Auth.internal_static_auth_LoginResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return top.zopx.goku.example.socket.proto.auth.Auth.internal_static_auth_LoginResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse.class, top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <pre>
     * 用户 Id,
     * 如果是 -1 则说明登录失败
     * </pre>
     *
     * <code>int64 userId = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }

    public static final int USERNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object userName_;
    /**
     * <pre>
     * 用户名称
     * </pre>
     *
     * <code>string userName = 2;</code>
     * @return The userName.
     */
    @java.lang.Override
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 用户名称
     * </pre>
     *
     * <code>string userName = 2;</code>
     * @return The bytes for userName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TICKET_FIELD_NUMBER = 3;
    private volatile java.lang.Object ticket_;
    /**
     * <pre>
     * 入场票据
     * </pre>
     *
     * <code>string ticket = 3;</code>
     * @return The ticket.
     */
    @java.lang.Override
    public java.lang.String getTicket() {
      java.lang.Object ref = ticket_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ticket_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 入场票据
     * </pre>
     *
     * <code>string ticket = 3;</code>
     * @return The bytes for ticket.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTicketBytes() {
      java.lang.Object ref = ticket_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ticket_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UKEY_FIELD_NUMBER = 4;
    private volatile java.lang.Object ukey_;
    /**
     * <pre>
     * 数字证书字符串
     * </pre>
     *
     * <code>string ukey = 4;</code>
     * @return The ukey.
     */
    @java.lang.Override
    public java.lang.String getUkey() {
      java.lang.Object ref = ukey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ukey_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 数字证书字符串
     * </pre>
     *
     * <code>string ukey = 4;</code>
     * @return The bytes for ukey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUkeyBytes() {
      java.lang.Object ref = ukey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ukey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UKEYEXPIREAT_FIELD_NUMBER = 5;
    private long ukeyExpireAt_;
    /**
     * <pre>
     * 数字正说过期时间
     * </pre>
     *
     * <code>sint64 ukeyExpireAt = 5;</code>
     * @return The ukeyExpireAt.
     */
    @java.lang.Override
    public long getUkeyExpireAt() {
      return ukeyExpireAt_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0L) {
        output.writeInt64(1, userId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ticket_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ticket_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ukey_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, ukey_);
      }
      if (ukeyExpireAt_ != 0L) {
        output.writeSInt64(5, ukeyExpireAt_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ticket_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ticket_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ukey_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, ukey_);
      }
      if (ukeyExpireAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(5, ukeyExpireAt_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse)) {
        return super.equals(obj);
      }
      top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse other = (top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse) obj;

      if (getUserId()
          != other.getUserId()) return false;
      if (!getUserName()
          .equals(other.getUserName())) return false;
      if (!getTicket()
          .equals(other.getTicket())) return false;
      if (!getUkey()
          .equals(other.getUkey())) return false;
      if (getUkeyExpireAt()
          != other.getUkeyExpireAt()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (37 * hash) + TICKET_FIELD_NUMBER;
      hash = (53 * hash) + getTicket().hashCode();
      hash = (37 * hash) + UKEY_FIELD_NUMBER;
      hash = (53 * hash) + getUkey().hashCode();
      hash = (37 * hash) + UKEYEXPIREAT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUkeyExpireAt());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 响应结果
     * </pre>
     *
     * Protobuf type {@code auth.LoginResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:auth.LoginResponse)
        top.zopx.goku.example.socket.proto.auth.Auth.LoginResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return top.zopx.goku.example.socket.proto.auth.Auth.internal_static_auth_LoginResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return top.zopx.goku.example.socket.proto.auth.Auth.internal_static_auth_LoginResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse.class, top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse.Builder.class);
      }

      // Construct using top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = 0L;

        userName_ = "";

        ticket_ = "";

        ukey_ = "";

        ukeyExpireAt_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return top.zopx.goku.example.socket.proto.auth.Auth.internal_static_auth_LoginResponse_descriptor;
      }

      @java.lang.Override
      public top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse getDefaultInstanceForType() {
        return top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse.getDefaultInstance();
      }

      @java.lang.Override
      public top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse build() {
        top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse buildPartial() {
        top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse result = new top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse(this);
        result.userId_ = userId_;
        result.userName_ = userName_;
        result.ticket_ = ticket_;
        result.ukey_ = ukey_;
        result.ukeyExpireAt_ = ukeyExpireAt_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse) {
          return mergeFrom((top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse other) {
        if (other == top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse.getDefaultInstance()) return this;
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (!other.getTicket().isEmpty()) {
          ticket_ = other.ticket_;
          onChanged();
        }
        if (!other.getUkey().isEmpty()) {
          ukey_ = other.ukey_;
          onChanged();
        }
        if (other.getUkeyExpireAt() != 0L) {
          setUkeyExpireAt(other.getUkeyExpireAt());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long userId_ ;
      /**
       * <pre>
       * 用户 Id,
       * 如果是 -1 则说明登录失败
       * </pre>
       *
       * <code>int64 userId = 1;</code>
       * @return The userId.
       */
      @java.lang.Override
      public long getUserId() {
        return userId_;
      }
      /**
       * <pre>
       * 用户 Id,
       * 如果是 -1 则说明登录失败
       * </pre>
       *
       * <code>int64 userId = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户 Id,
       * 如果是 -1 则说明登录失败
       * </pre>
       *
       * <code>int64 userId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <pre>
       * 用户名称
       * </pre>
       *
       * <code>string userName = 2;</code>
       * @return The userName.
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 用户名称
       * </pre>
       *
       * <code>string userName = 2;</code>
       * @return The bytes for userName.
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 用户名称
       * </pre>
       *
       * <code>string userName = 2;</code>
       * @param value The userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户名称
       * </pre>
       *
       * <code>string userName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户名称
       * </pre>
       *
       * <code>string userName = 2;</code>
       * @param value The bytes for userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ticket_ = "";
      /**
       * <pre>
       * 入场票据
       * </pre>
       *
       * <code>string ticket = 3;</code>
       * @return The ticket.
       */
      public java.lang.String getTicket() {
        java.lang.Object ref = ticket_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ticket_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 入场票据
       * </pre>
       *
       * <code>string ticket = 3;</code>
       * @return The bytes for ticket.
       */
      public com.google.protobuf.ByteString
          getTicketBytes() {
        java.lang.Object ref = ticket_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ticket_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 入场票据
       * </pre>
       *
       * <code>string ticket = 3;</code>
       * @param value The ticket to set.
       * @return This builder for chaining.
       */
      public Builder setTicket(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ticket_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 入场票据
       * </pre>
       *
       * <code>string ticket = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearTicket() {
        
        ticket_ = getDefaultInstance().getTicket();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 入场票据
       * </pre>
       *
       * <code>string ticket = 3;</code>
       * @param value The bytes for ticket to set.
       * @return This builder for chaining.
       */
      public Builder setTicketBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ticket_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ukey_ = "";
      /**
       * <pre>
       * 数字证书字符串
       * </pre>
       *
       * <code>string ukey = 4;</code>
       * @return The ukey.
       */
      public java.lang.String getUkey() {
        java.lang.Object ref = ukey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ukey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 数字证书字符串
       * </pre>
       *
       * <code>string ukey = 4;</code>
       * @return The bytes for ukey.
       */
      public com.google.protobuf.ByteString
          getUkeyBytes() {
        java.lang.Object ref = ukey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ukey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 数字证书字符串
       * </pre>
       *
       * <code>string ukey = 4;</code>
       * @param value The ukey to set.
       * @return This builder for chaining.
       */
      public Builder setUkey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ukey_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 数字证书字符串
       * </pre>
       *
       * <code>string ukey = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearUkey() {
        
        ukey_ = getDefaultInstance().getUkey();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 数字证书字符串
       * </pre>
       *
       * <code>string ukey = 4;</code>
       * @param value The bytes for ukey to set.
       * @return This builder for chaining.
       */
      public Builder setUkeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ukey_ = value;
        onChanged();
        return this;
      }

      private long ukeyExpireAt_ ;
      /**
       * <pre>
       * 数字正说过期时间
       * </pre>
       *
       * <code>sint64 ukeyExpireAt = 5;</code>
       * @return The ukeyExpireAt.
       */
      @java.lang.Override
      public long getUkeyExpireAt() {
        return ukeyExpireAt_;
      }
      /**
       * <pre>
       * 数字正说过期时间
       * </pre>
       *
       * <code>sint64 ukeyExpireAt = 5;</code>
       * @param value The ukeyExpireAt to set.
       * @return This builder for chaining.
       */
      public Builder setUkeyExpireAt(long value) {
        
        ukeyExpireAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 数字正说过期时间
       * </pre>
       *
       * <code>sint64 ukeyExpireAt = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearUkeyExpireAt() {
        
        ukeyExpireAt_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:auth.LoginResponse)
    }

    // @@protoc_insertion_point(class_scope:auth.LoginResponse)
    private static final top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse();
    }

    public static top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginResponse>
        PARSER = new com.google.protobuf.AbstractParser<LoginResponse>() {
      @java.lang.Override
      public LoginResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LoginResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public top.zopx.goku.example.socket.proto.auth.Auth.LoginResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_LoginRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_auth_LoginRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_auth_LoginResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_auth_LoginResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nauth.proto\022\004auth\"0\n\014LoginRequest\022\021\n\tlo" +
      "ginType\030\001 \001(\021\022\r\n\005login\030\002 \001(\t\"e\n\rLoginRes" +
      "ponse\022\016\n\006userId\030\001 \001(\003\022\020\n\010userName\030\002 \001(\t\022" +
      "\016\n\006ticket\030\003 \001(\t\022\014\n\004ukey\030\004 \001(\t\022\024\n\014ukeyExp" +
      "ireAt\030\005 \001(\022*<\n\007AuthDef\022\n\n\006_Dummy\020\000\022\021\n\r_L" +
      "oginRequest\020d\022\022\n\016_LoginResponse\020eB)\n\'top" +
      ".zopx.goku.example.socket.proto.authb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_auth_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_auth_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_auth_LoginRequest_descriptor,
        new java.lang.String[] { "LoginType", "Login", });
    internal_static_auth_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_auth_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_auth_LoginResponse_descriptor,
        new java.lang.String[] { "UserId", "UserName", "Ticket", "Ukey", "UkeyExpireAt", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
