spring:
  application:
    name: square-test
square:
  log:
    endurance: true

  distribution:
    redis:
      open: true
      address:
        - redis://192.168.1.9:6379
  sms:
    sms-li:
      open: true
      access-key-id: LTAI5t6eK2moGbmRxcpiA8KR
      access-secret: iDwtEcY62Chj9o4oqCw6R6xtp2bu1b
      sign-name: "精彩试玩"