spring:
  application:
    name: square-test

goku:
  material:
    minio:
      app-secret-id: ddd
      app-secret-key: dde
      endpoint: http://192.168.86.200:9100
      port: 9100
    oss:
      endpoint: https://192.168.86.200:9100
      app-secret-id: sadf
      app-secret-key: dfe
      support-https: true